# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import json
import logging
from typing import Any, Optional, Union
from urllib.parse import urlencode

from google.genai import _api_module
from google.genai import _common
from google.genai._common import get_value_by_path as getv
from google.genai._common import set_value_by_path as setv

from . import types

logger = logging.getLogger("vertexai_genai.skills")


def _GetSkillRequestParameters_to_vertex(
    from_object: Union[dict[str, Any], object],
    parent_object: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    to_object: dict[str, Any] = {}
    if getv(from_object, ["name"]) is not None:
        setv(to_object, ["_url", "name"], getv(from_object, ["name"]))

    if getv(from_object, ["config"]) is not None:
        setv(to_object, ["config"], getv(from_object, ["config"]))

    return to_object


class Skills(_api_module.BaseModule):
    """Class for managing Skills in the Skill Registry."""

    def get(
        self, *, name: str, config: Optional[types.GetSkillConfigOrDict] = None
    ) -> types.Skill:
        """
        Gets a Skill.
        """

        parameter_model = types._GetSkillRequestParameters(
            name=name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in the Gemini Enterprise Agent Platform (previously known as Vertex AI) client."
            )
        else:
            request_dict = _GetSkillRequestParameters_to_vertex(parameter_model)
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{name}".format_map(request_url_dict)
            else:
                path = "{name}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = self._api_client.request("get", path, request_dict, http_options)

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.Skill._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value


class AsyncSkills(_api_module.BaseModule):
    """Class for managing Skills in the Skill Registry."""

    async def get(
        self, *, name: str, config: Optional[types.GetSkillConfigOrDict] = None
    ) -> types.Skill:
        """
        Gets a Skill.
        """

        parameter_model = types._GetSkillRequestParameters(
            name=name,
            config=config,
        )

        request_url_dict: Optional[dict[str, str]]
        if not self._api_client.vertexai:
            raise ValueError(
                "This method is only supported in the Gemini Enterprise Agent Platform (previously known as Vertex AI) client."
            )
        else:
            request_dict = _GetSkillRequestParameters_to_vertex(parameter_model)
            request_url_dict = request_dict.get("_url")
            if request_url_dict:
                path = "{name}".format_map(request_url_dict)
            else:
                path = "{name}"

        query_params = request_dict.get("_query")
        if query_params:
            path = f"{path}?{urlencode(query_params)}"
        # TODO: remove the hack that pops config.
        request_dict.pop("config", None)

        http_options: Optional[types.HttpOptions] = None
        if (
            parameter_model.config is not None
            and parameter_model.config.http_options is not None
        ):
            http_options = parameter_model.config.http_options

        request_dict = _common.convert_to_dict(request_dict)
        request_dict = _common.encode_unserializable_types(request_dict)

        response = await self._api_client.async_request(
            "get", path, request_dict, http_options
        )

        response_dict = {} if not response.body else json.loads(response.body)

        return_value = types.Skill._from_response(
            response=response_dict,
            kwargs=(
                {
                    "config": {
                        "response_schema": getattr(
                            parameter_model.config, "response_schema", None
                        ),
                        "response_json_schema": getattr(
                            parameter_model.config, "response_json_schema", None
                        ),
                        "include_all_fields": getattr(
                            parameter_model.config, "include_all_fields", None
                        ),
                    }
                }
                if getattr(parameter_model, "config", None)
                else {}
            ),
        )

        self._api_client._verify_response(return_value)
        return return_value
